// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCvWG0EZvkWgZF8X4W5kbIIzYj19oD6_8',
    appId: '1:763497692708:web:204a9e15dacf19f55962b1',
    messagingSenderId: '763497692708',
    projectId: 'todoapp-3513f',
    authDomain: 'todoapp-3513f.firebaseapp.com',
    storageBucket: 'todoapp-3513f.firebasestorage.app',
    measurementId: 'G-WVZGFW8G61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzeMApXMd8_kegkxvVPkciX2fUOtV8oG4',
    appId: '1:763497692708:android:e9a823923dee33e65962b1',
    messagingSenderId: '763497692708',
    projectId: 'todoapp-3513f',
    storageBucket: 'todoapp-3513f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1hVee62GTC0u-dH16aoQEmzFYyyjeYwg',
    appId: '1:763497692708:ios:e14a32ac6086bf095962b1',
    messagingSenderId: '763497692708',
    projectId: 'todoapp-3513f',
    storageBucket: 'todoapp-3513f.firebasestorage.app',
    iosBundleId: 'com.as.chat.chatApp',
  );
}
